### ISSUE TITLE
Make animations more customizable for users

### ISSUE THREAD

**Issue by vplentinax** [launchtechllc/anojs#30]
-  Make the code extensible, reusable, and configurable.
-  Optimize the website so that point 1 is possible.

I meant that regardless of the technology we choose to use for animations, our codes are modules. Modules that allow the user to customize it according to their needs, since at this moment the user adapts to anojs and not the other way around, and in this way, the use of animations becomes complicated.

In anojs there should be the option to customize certain parameters of the code (number of balls, speed, colors, canvas size) and then be able to return the code to be used with the changes made.

**Comment by coderkalyan** [comment]
I completely agree with this. I would think that we would have configuration options for (not an exhaustive list):
* Canvas size
* number of objects (depends on animation)
* Speed of objects (depends on animation)
* Speed of animation, does it repeat or not?
* Color palette to use

**Comment by vplentinax** [comment]
Yes, any part that can be customizable depending on each animation.
