### ISSUE TITLE
[Invalid] Instagram link doesn't lead to Launch Tech Instagram 

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/anojs#56]
![image](https://user-images.githubusercontent.com/32065190/86035061-a7265280-ba09-11ea-98ac-0351ce518f5f.png)
![image](https://user-images.githubusercontent.com/32065190/86035085-b2797e00-ba09-11ea-9518-6bab31039329.png)

**Comment by jinhao27** [comment]
this issue was resolved. You can close this issue
